/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** key/value รбบไดщทбщง string (UTF-8) และ Buffer (binary) */
export interface Entry {
  key: string | Buffer
  value: string | Buffer
}
/** entry เดеยวทешไดщจาก iterator — value = null หมายถжง tombstone (คеยтถйกลบ) */
export interface IterEntry {
  key: Buffer
  value?: Buffer
}
/** สรщางไฟลт .xdb จาก entries — เรеยง key และกรองตбวซщำใหщเอง (ตбวหลбงสиดชนะ) */
export declare function writeTable(path: string, entries: Array<Entry>): void
/**
 * รวมหลายไฟลт .xdb เปчนไฟลтเดеยว (streaming — ตารางใหญшกчไมшกдน RAM)
 * key ซщำกбน: ไฟลтทешอยйшหลбงสиดใน `inputs` ชนะ
 * คзนจำนวน entries ในตารางผลลбพธт
 */
export declare function mergeTables(inputs: Array<string>, output: string): number
/** ตбวเลзอกการเปдด XdbStore */
export interface StoreOptions {
  /** จำนวน layers ทеш trigger compact อбตโนมбตд (default 8, 0 = ปдด) */
  compactThreshold?: number
  /** จำนวน entries ใน memtable ทеш trigger flush เปчน layer (default 4096, 0 = flush เองเทшานбщน) */
  flushEntries?: number
  /** fsync WAL ทиก put (default true) — false = เรчวขжщนแตшพбงกลางทางอาจเสеย put ลшาสиด */
  sync?: boolean
}
/** entry จาก store iterator (ตбด tombstone ออกแลщว) */
export interface StoreEntry {
  key: Buffer
  value: Buffer
}
/**
 * Reader แบบ mmap — เปдดครбщงเดеยวใชщไดщตลอดอายи process
 * ไฟลтเสеยหาย (checksum ไมшผшาน ฯลฯ) จะ throw แทนทешจะ crash
 */
export declare class XdbReader {
  constructor(path: string)
  /** จำนวน entries ทбщงหมดในตาราง */
  get len(): number
  /** จำนวน blocks (64KB ตшอ block โดยประมาณ) */
  get blockCount(): number
  /** คщนหา key → Buffer หรзอ null ถщาไมшพบ */
  get(key: string | Buffer): Buffer | null
  /** คщนหา key → UTF-8 string หรзอ null (ถщาไมшพบ หรзอคшาไมшใชш valid UTF-8) */
  getUtf8(key: string | Buffer): string | null
  has(key: string | Buffer): boolean
  /**
   * สรщาง iterator ไลшทиก entries เรеยงตาม key
   * สшง `start` เพзшอ seek: เรдшมทеш entry แรกทеш key >= start (ขщามไป block ตรง ๆ เลย)
   */
  iter(start?: string | Buffer | undefined | null): XdbIterator
}
/**
 * iterator แบบ native — ถзอ Arc ของ reader ไวщเอง จжงปลอดภбยแมщ JS จะ drop reader กшอน
 * ตรวจ CRC ครбщงเดеยวตшอ block (cache เปчน owned Vec)
 */
export declare class XdbIterator {
  /** คзน entry ถбดไปเปчน {key, value} หรзอ null เมзшอหมด — ไฟลтเสеยหายจะ throw */
  next(): IterEntry | null
}
/**
 * Store แบบ layered สำหรбบแอปทеш update แบบ realtime
 * put/delete = เขеยน WAL + memtable (เรчวมาก) / get = memtable → layers ตбวใหมшชนะ
 * compact อбตโนมбตдเมзшอ layers ถжง threshold (default 8)
 */
export declare class XdbStore {
  /** เปдด store ทеш directory นбщน (สรщางใหщถщายбงไมшมе) */
  constructor(path: string, options?: StoreOptions | undefined | null)
  /**
   * ปдด store + ปลด lock ของ directory — เรеยกเมзшอใชщงานเสรчจ
   * (ไมшเรеยกกчไดщ จะปลดเองตอน GC แตшจะถзอ lock ไวщนานกวшา)
   */
  close(): void
  /** จำนวน layers ปбจจиบбน */
  get layerCount(): number
  /** จำนวน entries ใน memtable ทешยбงไมшไดщ flush เปчน layer */
  get memtableLen(): number
  /** มе background compaction กำลбงรวอยйшหรзอไมш */
  get isCompacting(): boolean
  /** ดбน memtable ลง layer ถาวร + ลщาง WAL (ปกตд auto ตาม flushEntries อยйшแลщว) */
  flush(): void
  /** เพдшม/แกщคшา (upsert) — รбบไดщทбщง string และ Buffer, ไมшเรеยงกчไดщ, key ซщำตбวหลбงชนะ */
  put(entries: Array<Entry>): void
  /** ลบ keys — เขеยน tombstone กดคшาใน layer เกшา */
  delete(keys: Array<string | Buffer>): void
  /** คщนหา key → Buffer หรзอ null (ไมшมе หรзอ ถйกลบ) */
  get(key: string | Buffer): Buffer | null
  /** คщนหา key → UTF-8 string หรзอ null */
  getUtf8(key: string | Buffer): string | null
  has(key: string | Buffer): boolean
  /** รวมทиก layers เปчนไฟลтเดеยว — คзนคшาจำนวน layers หลбงทำ */
  compact(): number
  /** iterator มиมมองรวมของ store — สшง `start` เพзшอ seek ไปทеш key >= start */
  iter(start?: string | Buffer | undefined | null): XdbStoreIterator
}
/** iterator มиมมองรวมของ store — เรеยงตาม key, ใหมшชนะ, ตбดทешถйกลบ */
export declare class XdbStoreIterator {
  /** คзน entry ถбดไปเปчน {key, value} หรзอ null เมзшอหมด */
  next(): StoreEntry | null
}
